# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Apache.Tomcat9
PackageVersion: 9.0.89
PackageLocale: en-US
Publisher: Apache Software Foundation
PackageName: Apache Tomcat
License: Apache
Copyright: Copyright (c) 1999-2024 The Apache Software Foundation
ShortDescription: The Apache Tomcat® software is an open source implementation of the Jakarta Servlet, Pages, Expression Language, WebSocket, Annotations and Authentication specifications. These specifications are part of the Jakarta EE platform.
ManifestType: defaultLocale
ManifestVersion: 1.6.0
